const translations = {
  fa: {
    company: "رویین‌تن",
    tagline: "تأمین و فروش تخصصی آهن‌آلات و صنایع فلزی",
    nav_home: "صفحه اصلی",
    nav_products: "محصولات",
    nav_weight: "جدول وزن",
    nav_shipping: "هزینه حمل",
    nav_about: "درباره ما",
    nav_contact: "تماس با ما",
    phone: "۰۹۱۲۱۴۵۶۳۱۰",
    hero_title: "خرید مطمئن آهن‌آلات صنعتی و ساختمانی",
    hero_desc: "تأمین‌کننده تخصصی میلگرد، تیرآهن، ورق، پروفیل، نبشی، ناودانی، لوله، سیم مفتول و انواع پیچ، مهره و واشر با کیفیت تضمینی",
    btn_products: "مشاهده محصولات",
    btn_inquiry: "استعلام قیمت",
    btn_weight: "جدول وزن",
    btn_shipping: "محاسبه هزینه حمل",
    products_title: "محصولات ما",
    products_sub: "طیف کامل مقاطع فولادی و اتصالات",
    price_inquiry: "تماس / استعلام قیمت",
    feat1_t: "تضمین کیفیت",
    feat1_d: "محصولات استاندارد با ضمانت کتبی",
    feat2_t: "تحویل سریع",
    feat2_d: "ارسال به سراسر کشور",
    feat3_t: "مشاوره تخصصی",
    feat3_d: "راهنمایی قبل از خرید",
    feat4_t: "قیمت رقابتی",
    feat4_d: "بهترین نرخ بازار آهن",
    p_rebar: "میلگرد",
    p_rebar_d: "آجدار و ساده – سایزهای متنوع",
    p_beam: "تیرآهن",
    p_beam_d: "هاش و معمولی – استاندارد",
    p_sheet_black: "ورق سیاه",
    p_sheet_black_d: "فولادی نورد گرم",
    p_sheet_color: "ورق رنگی",
    p_sheet_color_d: "رنگ‌های متنوع صنعتی",
    p_sheet_galv: "ورق گالوانیزه",
    p_sheet_galv_d: "مقاوم در برابر خوردگی",
    p_sheet_oil: "ورق روغنی",
    p_sheet_oil_d: "نورد سرد – سطح صاف",
    p_sheet_steel: "ورق استیل",
    p_sheet_steel_d: "ضدزنگ – گریدهای مختلف",
    p_profile: "پروفیل",
    p_profile_d: "قوطی و نبشی پروفیل",
    p_angle: "نبشی",
    p_angle_d: "بال‌مساوی و نامساوی",
    p_channel: "ناودانی",
    p_channel_d: "سبک و سنگین",
    p_pipe: "لوله",
    p_pipe_d: "مانیسمان و درزدار",
    p_wire: "سیم مفتول",
    p_wire_d: "سیاه و گالوانیزه",
    p_fastener: "پیچ، مهره و واشر",
    p_fastener_d: "انواع اتصالات صنعتی",
    weight_title: "جدول وزن آهن‌آلات",
    weight_sub: "محاسبه وزن مقاطع فولادی",
    weight_calc: "محاسبه وزن پروفیل",
    w_thickness: "ضخامت (میلی‌متر)",
    w_length: "طول مقطع (میلی‌متر)",
    w_width: "عرض مقطع (میلی‌متر)",
    w_qty: "تعداد",
    w_calc_btn: "محاسبه وزن",
    w_unit: "وزن تقریبی واحد",
    w_total: "وزن تقریبی کل",
    w_kg: "کیلوگرم",
    tab_profile: "وزن پروفیل",
    tab_rebar: "وزن میلگرد آجدار",
    tab_beam: "وزن تیرآهن",
    tab_angle: "وزن نبشی",
    tab_channel: "وزن ناودانی",
    tab_pipe: "وزن لوله",
    shipping_title: "محاسبه هزینه حمل",
    shipping_sub: "هزینه حمل بار از مبدأ بنگاه تهران",
    shipping_desc: "با انتخاب مقصد، هزینه تقریبی حمل را مشاهده کنید.",
    ship_from: "مبدأ",
    ship_from_val: "تهران – بازار آهن شادآباد",
    ship_to: "مقصد",
    ship_select: "انتخاب کنید",
    ship_calc: "محاسبه",
    ship_single: "تک (۱۰ تن)",
    ship_double: "جفت (۱۵ تن)",
    ship_trailer: "تریلی (۲۲ تن)",
    ship_toman: "تومان",
    about_title: "درباره رویین‌تن",
    about_sub: "تأمین‌کننده تخصصی آهن‌آلات",
    about_p1: "شرکت رویین‌تن با تمرکز بر تأمین و فروش مقاطع فولادی و صنایع فلزی، در بازار آهن شادآباد تهران فعالیت می‌کند. ما طیف کاملی از میلگرد، تیرآهن، انواع ورق، پروفیل، نبشی، ناودانی، لوله، سیم مفتول و همچنین پیچ، مهره و واشر را به مشتریان صنعتی و ساختمانی عرضه می‌کنیم.",
    about_p2: "هدف ما ارائه محصول با کیفیت استاندارد، قیمت رقابتی و تحویل به‌موقع است. تیم فروش رویین‌تن آماده مشاوره تخصصی و استعلام قیمت روزانه می‌باشد.",
    contact_title: "تماس با ما",
    contact_sub: "آماده پاسخگویی به استعلام‌های شما",
    contact_address: "آدرس",
    contact_address_val: "تهران، بازار آهن شادآباد، بلوار طاووس، مجتمع ۱۷ شهریور، بلوک A، طبقه اول، پلاک ۲۲۸",
    contact_phone: "تلفن / واتساپ",
    contact_form_title: "فرم استعلام",
    c_name: "نام و نام خانوادگی",
    c_phone: "شماره تماس",
    c_product: "محصول مورد نظر",
    c_msg: "توضیحات",
    c_send: "ارسال استعلام",
    footer_desc: "تأمین و فروش تخصصی آهن‌آلات، مقاطع فولادی و اتصالات صنعتی در بازار آهن شادآباد تهران.",
    footer_quick: "دسترسی سریع",
    footer_contact: "اطلاعات تماس",
    footer_rights: "© تمامی حقوق برای رویین‌تن محفوظ است.",
    dim: "ابعاد",
    th2: "ضخامت ۲",
    th25: "ضخامت ۲٫۵",
    th3: "ضخامت ۳",
    th4: "ضخامت ۴"
  },
  en: {
    company: "Royintan",
    tagline: "Specialized supply of iron & steel products",
    nav_home: "Home",
    nav_products: "Products",
    nav_weight: "Weight Table",
    nav_shipping: "Shipping Cost",
    nav_about: "About",
    nav_contact: "Contact",
    phone: "09121456310",
    hero_title: "Reliable Industrial & Construction Steel Supply",
    hero_desc: "Specialized supplier of rebar, beams, sheets, profiles, angles, channels, pipes, wire, bolts, nuts and washers — guaranteed quality",
    btn_products: "View Products",
    btn_inquiry: "Price Inquiry",
    btn_weight: "Weight Table",
    btn_shipping: "Shipping Calculator",
    products_title: "Our Products",
    products_sub: "Full range of steel sections and fasteners",
    price_inquiry: "Call / Price Inquiry",
    feat1_t: "Quality Guarantee",
    feat1_d: "Standard products with written warranty",
    feat2_t: "Fast Delivery",
    feat2_d: "Nationwide shipping",
    feat3_t: "Expert Consulting",
    feat3_d: "Guidance before purchase",
    feat4_t: "Competitive Price",
    feat4_d: "Best market rates",
    p_rebar: "Rebar",
    p_rebar_d: "Ribbed & plain – various sizes",
    p_beam: "I-Beam",
    p_beam_d: "H & standard beams",
    p_sheet_black: "Black Sheet",
    p_sheet_black_d: "Hot-rolled steel",
    p_sheet_color: "Color Sheet",
    p_sheet_color_d: "Industrial coated sheets",
    p_sheet_galv: "Galvanized Sheet",
    p_sheet_galv_d: "Corrosion resistant",
    p_sheet_oil: "Cold-Rolled Sheet",
    p_sheet_oil_d: "Smooth surface finish",
    p_sheet_steel: "Stainless Sheet",
    p_sheet_steel_d: "Various grades",
    p_profile: "Profile / Tube",
    p_profile_d: "Square & rectangular",
    p_angle: "Angle",
    p_angle_d: "Equal & unequal",
    p_channel: "Channel",
    p_channel_d: "Light & heavy",
    p_pipe: "Pipe",
    p_pipe_d: "Seamless & welded",
    p_wire: "Wire",
    p_wire_d: "Black & galvanized",
    p_fastener: "Bolts, Nuts & Washers",
    p_fastener_d: "Industrial fasteners",
    weight_title: "Steel Weight Tables",
    weight_sub: "Calculate section weights",
    weight_calc: "Profile Weight Calculator",
    w_thickness: "Thickness (mm)",
    w_length: "Section length (mm)",
    w_width: "Section width (mm)",
    w_qty: "Quantity",
    w_calc_btn: "Calculate",
    w_unit: "Approx. unit weight",
    w_total: "Approx. total weight",
    w_kg: "kg",
    tab_profile: "Profile",
    tab_rebar: "Rebar",
    tab_beam: "Beam",
    tab_angle: "Angle",
    tab_channel: "Channel",
    tab_pipe: "Pipe",
    shipping_title: "Shipping Cost Calculator",
    shipping_sub: "Freight from Tehran iron market",
    shipping_desc: "Select destination to see approximate shipping cost.",
    ship_from: "Origin",
    ship_from_val: "Tehran – Shadabad Iron Market",
    ship_to: "Destination",
    ship_select: "Select",
    ship_calc: "Calculate",
    ship_single: "Single (10 t)",
    ship_double: "Double (15 t)",
    ship_trailer: "Trailer (22 t)",
    ship_toman: "Toman",
    about_title: "About Royintan",
    about_sub: "Specialized steel supplier",
    about_p1: "Royintan supplies and trades steel sections and metal products at Tehran Shadabad Iron Market. We offer rebar, beams, sheets, profiles, angles, channels, pipes, wire, as well as bolts, nuts and washers to industrial and construction clients.",
    about_p2: "Our goal is standard quality, competitive pricing and on-time delivery. The sales team is ready for daily price inquiries and technical advice.",
    contact_title: "Contact Us",
    contact_sub: "Ready for your inquiries",
    contact_address: "Address",
    contact_address_val: "Tehran, Shadabad Iron Market, Tavoos Blvd, 17 Shahrivar Complex, Block A, 1st floor, No. 228",
    contact_phone: "Phone / WhatsApp",
    contact_form_title: "Inquiry Form",
    c_name: "Full name",
    c_phone: "Phone number",
    c_product: "Desired product",
    c_msg: "Details",
    c_send: "Send Inquiry",
    footer_desc: "Specialized supply of iron, steel sections and industrial fasteners at Tehran Shadabad Iron Market.",
    footer_quick: "Quick Links",
    footer_contact: "Contact Info",
    footer_rights: "© All rights reserved for Royintan.",
    dim: "Size",
    th2: "Thk 2",
    th25: "Thk 2.5",
    th3: "Thk 3",
    th4: "Thk 4"
  },
  ar: {
    company: "رويين‌تن",
    tagline: "توريد متخصص لحديد ومنتجات الصلب",
    nav_home: "الرئيسية",
    nav_products: "المنتجات",
    nav_weight: "جدول الأوزان",
    nav_shipping: "تكلفة الشحن",
    nav_about: "من نحن",
    nav_contact: "اتصل بنا",
    phone: "09121456310",
    hero_title: "توريد موثوق لحديد البناء والصناعة",
    hero_desc: "مورد متخصص لحديد التسليح والكمرات والصفائح والبروفايل والزوايا والقنوات والأنابيب والأسلاك والبراغي والصواميل والغسالات بجودة مضمونة",
    btn_products: "عرض المنتجات",
    btn_inquiry: "استعلام السعر",
    btn_weight: "جدول الأوزان",
    btn_shipping: "حاسبة الشحن",
    products_title: "منتجاتنا",
    products_sub: "مجموعة كاملة من المقاطع الفولاذية والوصلات",
    price_inquiry: "اتصل / استعلام السعر",
    feat1_t: "ضمان الجودة",
    feat1_d: "منتجات قياسية بضمان مكتوب",
    feat2_t: "توصيل سريع",
    feat2_d: "شحن إلى جميع أنحاء البلاد",
    feat3_t: "استشارات متخصصة",
    feat3_d: "إرشاد قبل الشراء",
    feat4_t: "أسعار تنافسية",
    feat4_d: "أفضل أسعار السوق",
    p_rebar: "حديد التسليح",
    p_rebar_d: "مضلع وناعم – أحجام متنوعة",
    p_beam: "كمرة",
    p_beam_d: "هاش وقياسية",
    p_sheet_black: "صفيحة سوداء",
    p_sheet_black_d: "فولاذ مدرفل على الساخن",
    p_sheet_color: "صفيحة ملونة",
    p_sheet_color_d: "طلاء صناعي متنوع",
    p_sheet_galv: "صفيحة مجلفنة",
    p_sheet_galv_d: "مقاومة للتآكل",
    p_sheet_oil: "صفيحة مدهونة",
    p_sheet_oil_d: "مدرفلة على البارد",
    p_sheet_steel: "صفيحة استيل",
    p_sheet_steel_d: "مقاوم للصدأ",
    p_profile: "بروفايل",
    p_profile_d: "مربع ومستطيل",
    p_angle: "زاوية",
    p_angle_d: "متساوية وغير متساوية",
    p_channel: "قناة",
    p_channel_d: "خفيفة وثقيلة",
    p_pipe: "أنبوب",
    p_pipe_d: "سلس وملحوم",
    p_wire: "سلك",
    p_wire_d: "أسود ومجلفن",
    p_fastener: "براغي وصواميل وغسالات",
    p_fastener_d: "وصلات صناعية",
    weight_title: "جداول أوزان الحديد",
    weight_sub: "حساب وزن المقاطع الفولاذية",
    weight_calc: "حاسبة وزن البروفايل",
    w_thickness: "السماكة (مم)",
    w_length: "طول المقطع (مم)",
    w_width: "عرض المقطع (مم)",
    w_qty: "العدد",
    w_calc_btn: "احسب الوزن",
    w_unit: "الوزن التقريبي للوحدة",
    w_total: "الوزن التقريبي الكلي",
    w_kg: "كغ",
    tab_profile: "بروفايل",
    tab_rebar: "حديد تسليح",
    tab_beam: "كمرة",
    tab_angle: "زاوية",
    tab_channel: "قناة",
    tab_pipe: "أنبوب",
    shipping_title: "حاسبة تكلفة الشحن",
    shipping_sub: "تكلفة النقل من سوق حديد طهران",
    shipping_desc: "اختر الوجهة لعرض التكلفة التقريبية.",
    ship_from: "المنشأ",
    ship_from_val: "طهران – سوق حديد شادآباد",
    ship_to: "الوجهة",
    ship_select: "اختر",
    ship_calc: "احسب",
    ship_single: "فردي (١٠ طن)",
    ship_double: "مزدوج (١٥ طن)",
    ship_trailer: "مقطورة (٢٢ طن)",
    ship_toman: "تومان",
    about_title: "عن رويين‌تن",
    about_sub: "مورد متخصص للصلب",
    about_p1: "تعمل شركة رويين‌تن في توريد وبيع المقاطع الفولاذية ومنتجات المعادن في سوق حديد شادآباد بطهران. نوفر حديد التسليح والكمرات والصفائح والبروفايل والزوايا والقنوات والأنابيب والأسلاك بالإضافة إلى البراغي والصواميل والغسالات.",
    about_p2: "هدفنا الجودة القياسية والأسعار التنافسية والتسليم في الوقت المحدد. فريق المبيعات جاهز للاستعلام اليومي عن الأسعار والاستشارات.",
    contact_title: "اتصل بنا",
    contact_sub: "جاهزون لاستعلاماتكم",
    contact_address: "العنوان",
    contact_address_val: "طهران، سوق حديد شادآباد، شارع طاووس، مجمع ١٧ شهريور، بلوك A، الطابق الأول، رقم ٢٢٨",
    contact_phone: "هاتف / واتساب",
    contact_form_title: "نموذج الاستعلام",
    c_name: "الاسم الكامل",
    c_phone: "رقم الهاتف",
    c_product: "المنتج المطلوب",
    c_msg: "التفاصيل",
    c_send: "إرسال الاستعلام",
    footer_desc: "توريد متخصص للحديد والمقاطع الفولاذية والوصلات الصناعية في سوق حديد شادآباد بطهران.",
    footer_quick: "روابط سريعة",
    footer_contact: "معلومات الاتصال",
    footer_rights: "© جميع الحقوق محفوظة لرويين‌تن.",
    dim: "الأبعاد",
    th2: "سماكة ٢",
    th25: "سماكة ٢٫٥",
    th3: "سماكة ٣",
    th4: "سماكة ٤"
  }
};

function setLang(lang) {
  const t = translations[lang];
  if (!t) return;
  document.documentElement.lang = lang;
  document.documentElement.dir = lang === 'en' ? 'ltr' : 'rtl';
  document.body.classList.toggle('ltr', lang === 'en');
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) el.textContent = t[key];
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (t[key] !== undefined) el.placeholder = t[key];
  });
  localStorage.setItem('royintan-lang', lang);
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });
}

document.addEventListener('DOMContentLoaded', () => {
  const saved = localStorage.getItem('royintan-lang') || 'fa';
  setLang(saved);
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.addEventListener('click', () => setLang(btn.dataset.lang));
  });
});
